### ISSUE TITLE
React & Redux group project: Set up your Kanban board

### ISSUE THREAD

**Issue by muskan2532150** [muskan2532150/Space-Travelers-Hub#17]
[Link to Kanban Board](https://github.com/users/muskan2532150/projects/3)

### Team Members
- Muskan Gupta
- Kibirige John

**Comment by addod19** [comment]
### Hi @muskan2532150 and @John-Kibirige, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Issue is created by the student :100: 
- [x] List of team members listed out :rocket: 

## Required Changes ♻️
_Check the comments under the review._
- [ ] It would be better if the link given in the issue takes us to the project page, however, here is what we were presented with as seen below
![Screenshot from 2022-09-26 13-05-40](https://user-images.githubusercontent.com/46388113/192284410-a0c35f20-ec5b-44be-975e-451159f8ef24.png)
Instead of this
![Screenshot from 2022-09-26 13-06-45](https://user-images.githubusercontent.com/46388113/192284577-5cd10712-0be8-4b03-8fb8-8153c9aec878.png)




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @muskan2532150 and @John-Kibirige,

✔️ Good documentation

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
